services:
  catalogdb:
    container_name: catalogdb
    environment:
      - POSTGRES_USER=catalog
      - POSTGRES_PASSWORD=C4tal0g
      - POSTGRES_DB=catalog
    restart: always
    ports:
        - "5432:5432"
    volumes:
      - postgres_catalog:/var/lib/postgresql/data/    

  catalog.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__Database=Server=catalogdb;Port=5432;Database=catalog;User Id=catalog;Password=C4tal0g;Include Error Detail=true;Ssl mode=Disable
    ports:
      - "8080"
      - "8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro