services:
  catalogdb:
    image: postgres
  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Catalog/Catalog.Api/Dockerfile
volumes:
  postgres_catalog:
